name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Set up Bun environment
        uses: ./.github/actions/setup-project

      - name: Restore or cache Next.js build
        uses: actions/cache@v5
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: nextjs-${{ hashFiles('bun.lock') }}-${{ hashFiles('src/**') }}

      - name: Build Next.js
        run: bun run build-local
        env:
          NEXT_PUBLIC_SENTRY_DISABLED: 'true' # Only upload Sentry source maps in deployment
          NEXT_PUBLIC_APP_URL: http://localhost:3008

      - name: Cache Next.js build output
        if: success()
        uses: actions/cache/save@v5
        with:
          path: |
            .next
            next-env.d.ts
          key: nextjs-build-${{ github.sha }}

  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Set up Bun environment
        uses: ./.github/actions/setup-project

      - name: Run unit tests
        uses: docker://mcr.microsoft.com/playwright:v1.60.0
        with:
          args: npm run test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Fix test results permission # Give permissions to test results needed by Chromatic
        run: |
          sudo chmod -R 777 test-results

      - name: Run visual regression tests
        uses: chromaui/action@v17
        with:
          playwright: true
          exitOnceUploaded: true # Speed up by skipping the build results
          outputDir: storybook-static
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
